language: python
python:
  - 3.5

install:
  - pip install sphinx

script:
  - cd $TRAVIS_BUILD_DIR
  - make html

# Deploy using travis builtin GitHub Pages support
deploy:
  provider: pages
  # target_branch: gh-pages # Branch to force push to, defaults to gh-pages
  skip_cleanup: true
  local_dir: build/html
  github_token: $GITHUB_API_KEY
  on:
    branch: master